---
language: ruby
cache: bundler

matrix:
    fast_finish: true
    include:
        - rvm: 2.1
          env: PUPPET_VERSION="4.5.0" STRICT_VARIABLES="yes"
          services: docker
          sudo: required
          script: bundle exec rake
        - rvm: 2.2
          env: PUPPET_VERSION="4.6.1" STRICT_VARIABLES="yes"
          services: docker
          sudo: required
          script: bundle exec rake
        - rvm: 2.2
          env: PUPPET_VERSION="4.6.1" STRICT_VARIABLES="yes" BEAKER_set="centos-7-x64"
          services: docker
          sudo: required
          script: bundle exec rake
notifications:
    email: false
